import type { DashboardKpi, FunnelStage } from "@/types";

export const dashboardKPIs: DashboardKpi[] = [
  {
    title: "Impressions",
    before: "",
    value: "184.2",
    suffix: "M",
    change: "+ 6.4%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Reach",
    before: "",
    value: "22.4",
    suffix: "M",
    change: "+ 4.9%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Freq / Users",
    before: "",
    value: "8.2",
    suffix: "X",
    change: "+ 1.8%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Mobile CTR",
    before: "",
    value: "0.82",
    suffix: "%",
    change: "+ 3.1%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "CPM",
    before: "$",
    value: "7.45",
    suffix: "",
    change: "- 2.2%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Visit Lift",
    before: "",
    value: "18.7",
    suffix: "%",
    change: "+ 5.6%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Dwell time",
    before: "",
    value: "52",
    suffix: "sec",
    change: "- 1.4%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Sales lift",
    before: "",
    value: "9.5",
    suffix: "%",
    change: "+ 5.2%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "New to brand",
    before: "",
    value: "27",
    suffix: "%",
    change: "+ 2.0%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Basket lift",
    before: "",
    value: "6.1",
    suffix: "%",
    change: "+ 1.7%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Cross buy",
    before: "",
    value: "14.3",
    suffix: "%",
    change: "+ 3.5%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Offer redeem",
    before: "",
    value: "2.6",
    suffix: "%",
    change: "- 2.4%",
    tooltipMsg: "Tooltip content can be used here",
  },
];

export const funnelData: FunnelStage[] = [
  {
    label: "Ad impressions",
    sub: "DOOH + Mobile",
    value: "184.2M",
    width: 320,
    color: "#ff1975",
  },
  {
    label: "Unique Reach",
    sub: "Devices exposed",
    value: "22.4M",
    width: 280,
    color: "#ff4b8f",
  },
  {
    label: "Mobile engagements",
    sub: "Clicks + Actions",
    value: "183K",
    width: 240,
    color: "#ff73aa",
  },
  {
    label: "Store visits",
    sub: "Attributed",
    value: "512K",
    width: 200,
    color: "#ff9bc2",
  },
  {
    label: "In-store purchasers",
    sub: "Video views",
    value: "142K",
    width: 160,
    color: "#ffc1d8",
  },
  {
    label: "Repeat purchasers",
    sub: "Loyal customers",
    value: "38K",
    width: 120,
    color: "#ffe1ee",
  },
];
