import type {
  DashboardKpi,
  FunnelStage,
  performanceByRegionType,
} from "@/types";

export const dashboardKPIs: DashboardKpi[] = [
  {
    title: "Impressions",
    before: "",
    value: "184.2",
    suffix: "M",
    change: "+ 6.4%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Reach",
    before: "",
    value: "22.4",
    suffix: "M",
    change: "+ 4.9%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Freq / Users",
    before: "",
    value: "8.2",
    suffix: "X",
    change: "+ 1.8%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Mobile CTR",
    before: "",
    value: "0.82",
    suffix: "%",
    change: "+ 3.1%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "CPM",
    before: "$",
    value: "7.45",
    suffix: "",
    change: "- 2.2%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Visit Lift",
    before: "",
    value: "18.7",
    suffix: "%",
    change: "+ 5.6%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Dwell time",
    before: "",
    value: "52",
    suffix: "sec",
    change: "- 1.4%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Sales lift",
    before: "",
    value: "9.5",
    suffix: "%",
    change: "+ 5.2%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "New to brand",
    before: "",
    value: "27",
    suffix: "%",
    change: "+ 2.0%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Basket lift",
    before: "",
    value: "6.1",
    suffix: "%",
    change: "+ 1.7%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Cross buy",
    before: "",
    value: "14.3",
    suffix: "%",
    change: "+ 3.5%",
    tooltipMsg: "Tooltip content can be used here",
  },
  {
    title: "Offer redeem",
    before: "",
    value: "2.6",
    suffix: "%",
    change: "- 2.4%",
    tooltipMsg: "Tooltip content can be used here",
  },
];
export const doohKPIs: DashboardKpi[] = [
  {
    title: "Food traffic lift",
    before: "",
    value: "6.4",
    suffix: "%",
    change: "+ 0.7%",
    tooltipMsg: "Increase in store foot traffic driven by campaign exposure",
  },
  {
    title: "Category sales lift",
    before: "",
    value: "11.2",
    suffix: "%",
    change: "+ 6.1%",
    tooltipMsg: "Sales growth within the advertised product category",
  },
  {
    title: "Total impressions",
    before: "",
    value: "4.7",
    suffix: "%",
    change: "- 2.9%",
    tooltipMsg: "Change in total impressions delivered across channels",
  },
  {
    title: "Item level sales lift",
    before: "",
    value: "18.7",
    suffix: "%",
    change: "+ 9.4%",
    tooltipMsg: "Sales lift at individual item or SKU level",
  },
  {
    title: "New to brand shoppers",
    before: "",
    value: "9.3",
    suffix: "%",
    change: "+ 11.2%",
    tooltipMsg:
      "Percentage of shoppers purchasing the brand for the first time",
  },
  {
    title: "Basket size change",
    before: "",
    value: "7.8",
    suffix: "%",
    change: "+ 1.4%",
    tooltipMsg: "Average change in number of items per transaction",
  },
  {
    title: "Dwell time",
    before: "",
    value: "2.1",
    suffix: "%",
    change: "- 3.2%",
    tooltipMsg: "Change in average time spent in store",
  },
  {
    title: "Frequency per shopper",
    before: "",
    value: "1.6",
    suffix: "%",
    change: "- 13.7%",
    tooltipMsg: "Change in visit frequency per shopper",
  },
  {
    title: "Return visit rate",
    before: "",
    value: "5.1",
    suffix: "%",
    change: "+ 7.6%",
    tooltipMsg: "Increase in repeat visits after initial exposure",
  },
  {
    title: "Reach by store",
    before: "",
    value: "14.5",
    suffix: "%",
    change: "+ 15.1%",
    tooltipMsg: "Increase in unique reach across store locations",
  },
  {
    title: "Conversion to purchase",
    before: "",
    value: "3.8",
    suffix: "%",
    change: "+ 5.3%",
    tooltipMsg: "Lift in conversion from exposure to purchase",
  },
  {
    title: "Incremental reach",
    before: "",
    value: "3.7",
    suffix: "%",
    change: "- 4.8%",
    tooltipMsg: "Net new reach beyond baseline audience",
  },
];
export const storeTrafficKpi: DashboardKpi[] = [
  {
    title: "Sales",
    before: "",
    value: "42.8",
    suffix: "M",
    change: "LY + 1.4%",
    tooltipMsg: "Total sales revenue compared year over year",
  },
  {
    title: "Sales units",
    before: "",
    value: "26.9",
    suffix: "M",
    change: "LY - 3.1%",
    tooltipMsg: "Total number of units sold year over year",
  },
  {
    title: "Shopper traffic count",
    before: "",
    value: "182",
    suffix: "K visits",
    change: "LY + 3.2%",
    tooltipMsg: "Total number of shopper visits compared year over year",
  },
  {
    title: "Gross profit",
    before: "",
    value: "14.2",
    suffix: "M",
    change: "LY - 9.8%",
    tooltipMsg: "Gross profit generated after cost of goods sold",
  },
  {
    title: "Gross profit rate",
    before: "",
    value: "33.2",
    suffix: "%",
    change: "LY - 1.0%",
    tooltipMsg: "Gross profit as a percentage of total sales",
  },
  {
    title: "Trip conversion rate",
    before: "",
    value: "41.6",
    suffix: "%",
    change: "LY - 0.4%",
    tooltipMsg: "Percentage of store trips that resulted in a purchase",
  },
  {
    title: "Inventory on-hand",
    before: "",
    value: "4.0",
    suffix: "%",
    change: "LY + 2.4%",
    tooltipMsg: "Percentage change in inventory levels held on hand",
  },
  {
    title: "Inventory on-hand units",
    before: "",
    value: "2.1",
    suffix: "%",
    change: "LY + 1.9%",
    tooltipMsg: "Change in inventory unit count year over year",
  },
  {
    title: "Basket / h-value items",
    before: "",
    value: "32.5",
    suffix: "%",
    change: "LY + 1.1%",
    tooltipMsg: "Share of baskets containing high-value items",
  },
  {
    title: "Avg. unit selling price",
    before: "",
    value: "1.59",
    suffix: "%",
    change: "LY + 4.7%",
    tooltipMsg: "Average selling price per unit compared year over year",
  },
  {
    title: "Avg. unit / trans.",
    before: "",
    value: "1.22",
    suffix: "",
    change: "LY - 0.6%",
    tooltipMsg: "Average number of units per transaction",
  },
  {
    title: "Promo lift rate",
    before: "",
    value: "6.8",
    suffix: "%",
    change: "LY + 2.4%",
    tooltipMsg: "Incremental lift in sales driven by promotions",
  },
];
export const basketInsightsKpi: DashboardKpi[] = [
  {
    title: "Basket spend",
    before: "",
    value: "19.40",
    suffix: "",
    change: "LY + 3.2%",
    tooltipMsg: "Average spend per basket compared year over year",
  },
  {
    title: "Basket size",
    before: "",
    value: "3.1",
    suffix: "",
    change: "LY + 4.4%",
    tooltipMsg: "Average number of items per basket",
  },
  {
    title: "Top add on",
    before: "",
    value: "14.8",
    suffix: "% chips",
    change: "LY + 0.9%",
    tooltipMsg: "Most common add-on item share within baskets",
  },
  {
    title: "Add on snacks",
    before: "",
    value: "28.6",
    suffix: "%",
    change: "LY + 1.1%",
    tooltipMsg: "Share of baskets that included snack add-ons",
  },
  {
    title: "Multi unit",
    before: "",
    value: "18.7",
    suffix: "%",
    change: "LY - 0.8%",
    tooltipMsg: "Percentage of transactions with multiple units purchased",
  },
  {
    title: "Attach rate",
    before: "",
    value: "41.2",
    suffix: "%",
    change: "LY + 1.9%",
    tooltipMsg: "Rate at which additional items are attached to purchases",
  },
  {
    title: "Promo lift",
    before: "",
    value: "8.4",
    suffix: "%",
    change: "LY + 2.3%",
    tooltipMsg: "Incremental sales lift driven by promotional activity",
  },
  {
    title: "Daypart mix",
    before: "",
    value: "40.5",
    suffix: "%",
    change: "sLY - 0.3%",
    tooltipMsg: "Distribution of purchases across key dayparts",
  },
  {
    title: "High value",
    before: "",
    value: "16.2",
    suffix: "K",
    change: "LY + 2.5%",
    tooltipMsg: "Number of high-value transactions",
  },
  {
    title: "Pair strength",
    before: "",
    value: "34.7",
    suffix: "%",
    change: "LY + 1.4%",
    tooltipMsg: "Strength of frequently paired product combinations",
  },
  {
    title: "Add on lift",
    before: "",
    value: "6.9",
    suffix: "%",
    change: "LY + 1.1%",
    tooltipMsg: "Lift in add-on item purchases compared year over year",
  },
  {
    title: "SKU value share",
    before: "",
    value: "32.3",
    suffix: "%",
    change: "LY - 0.4%",
    tooltipMsg: "Share of total value contributed by key SKUs",
  },
];
export const funnelData: FunnelStage[] = [
  {
    label: "Ad impressions",
    sub: "DOOH + Mobile",
    value: "184.2M",
    width: 320,
    color: "#ff1975",
  },
  {
    label: "Unique Reach",
    sub: "Devices exposed",
    value: "22.4M",
    width: 280,
    color: "#ff4b8f",
  },
  {
    label: "Mobile engagements",
    sub: "Clicks + Actions",
    value: "183K",
    width: 240,
    color: "#ff73aa",
  },
  {
    label: "Store visits",
    sub: "Attributed",
    value: "512K",
    width: 200,
    color: "#ff9bc2",
  },
  {
    label: "In-store purchasers",
    sub: "Video views",
    value: "142K",
    width: 160,
    color: "#ffc1d8",
  },
  {
    label: "Repeat purchasers",
    sub: "Loyal customers",
    value: "38K",
    width: 120,
    color: "#ffe1ee",
  },
];
export const performanceByRegion: performanceByRegionType[] = [
  { region: "Ontario", progress: 100, change: "+4.1%" },
  { region: "British Columbia", progress: 50, change: "+2.2%" },
  { region: "Quebec", progress: 30, change: "+1.5%" },
  { region: "Alberta", progress: 10, change: "+0.8%" },
];
