import funnelChart from "@/assets/funnelChart.svg";
import PageHeader from "@/components/home/PageHeader";
import CardHeader from "@/components/CardHeader";
import DashboardModal from "@/components/DashboardModal";
import type { DashboardKpi } from "@/types";
import { dashboardKPIs, funnelData, performanceByRegion } from "../../allJSONs";
import { useState } from "react";
import DetailBox from "@/components/ui/DetailBox";
import {
  AreaChart,
  Area,
  XAxis,
  YAxis,
  Tooltip,
  ResponsiveContainer,
} from "recharts";
import { Progress } from "@/components/ui/progress";
import {
  CheckCircleIcon,
  CircleCheckIcon,
  Clock1,
  Clock12Icon,
  LightbulbIcon,
  TrendingUp,
} from "lucide-react";
import AiInlineRecommendation from "@/components/ui/AiInlineRecommendation";

export default function Home() {
  const data = [
    { name: "jan", value: 0.28 },
    { name: "feb", value: 0.35 },
    { name: "mar", value: 0.5 },
    { name: "apr", value: 0.62 },
    { name: "may", value: 0.75 },
    { name: "jun", value: 0.82 },
  ];

  const funnelSteps = [
    { label: "Impressions", value: "184.2M" },
    { label: "Engagement", value: "0.82%" },
    { label: "Consideration", value: "183K" },
    { label: "Store visits", value: "512K" },
    { label: "Loyalty", value: "38K" },
  ];
  const gradients = [
    "linear-gradient(135deg, #ff8cc3, #ff4b9a)",
    "linear-gradient(135deg, #ff6fb0, #ff3388)",
    "linear-gradient(135deg, #ff5fa2, #ff1f7a)",
    "linear-gradient(135deg, #ff4b9a, #e91e63)",
    "linear-gradient(135deg, #ff3388, #d81b60)",
  ];
  const kpiDeepDive = [
    {
      title: "CTR",
      before: "",
      value: "0.82",
      suffix: "%",
      change: "+ 9.8%",
      tooltipMsg: "Click-through rate across all served impressions",
    },
    {
      title: "Impressions",
      before: "",
      value: "22.3",
      suffix: "M",
      change: "+ 6.4%",
      tooltipMsg: "Total number of ad impressions delivered",
    },
    {
      title: "Clicks",
      before: "",
      value: "183",
      suffix: "K",
      change: "+ 9.7%",
      tooltipMsg: "Total number of clicks generated by the campaign",
    },
    {
      title: "Avg / CPC",
      before: "",
      value: "3,112",
      suffix: "",
      change: "- 2.2%",
      tooltipMsg: "Average cost per click across all placements",
    },
    {
      title: "Visit conversion",
      before: "",
      value: "2.3",
      suffix: "%",
      change: "+ 1.5%",
      tooltipMsg: "Percentage of clicks that resulted in a store visit",
    },
  ];
  const [selectedKpi, setSelectedKpi] = useState<DashboardKpi | null>(null);

  return (
    <section className="w-full flex flex-col gap-y-7">
      <PageHeader title="Marketing strategic campaign" chips={true} />
      <div className="w-full flex flex-col md:flex-row gap-5">
        <div className="card w-full max-w-200">
          <CardHeader title="Dashboard" />
          <div className="cardBody grid grid-cols-2 md:grid-cols-3 gap-3 md:gap-y-4 md:gap-x-7">
            {dashboardKPIs.map((kpi) => (
              <div key={kpi.title} onClick={() => setSelectedKpi(kpi)}>
                <DetailBox kpi={kpi} tooltipMsg={kpi.tooltipMsg} />
              </div>
            ))}
          </div>
          {selectedKpi && (
            <DashboardModal
              isOpen={!!selectedKpi}
              onClose={() => setSelectedKpi(null)}
              title={`KPI deep dive - ${selectedKpi.title}`}
            >
              <div className="flex flex-col gap-4">
                <div className="card">
                  <CardHeader title="" />
                  <div className="grid grid-cols-2 md:grid-cols-5 gap-3 ">
                    {kpiDeepDive.map((kpi, _) => {
                      return <DetailBox key={kpi.value} kpi={kpi} />;
                    })}
                  </div>
                </div>
                <div className="w-full flex flex-col md:flex-row gap-5 ">
                  <div className="w-full max-w-200 flex flex-col gap-3">
                    <div className="card">
                      <div className="flex flex-col md:flex-row justify-between gap-x-10">
                        <div className="w-full max-w-100">
                          <div className="flex flex-col justify-between">
                            <h3 className="text-lg font-semibold leading-6 text-white mb-4 md:mb-8">
                              {selectedKpi.title} trend
                            </h3>
                            <div className="w-full">
                              <ResponsiveContainer width="100%" height={230}>
                                <AreaChart data={data}>
                                  <defs>
                                    <linearGradient
                                      id="area"
                                      x1="0"
                                      y1="0"
                                      x2="0"
                                      y2="1"
                                    >
                                      <stop
                                        offset="0%"
                                        stopColor="#ff1f7a"
                                        stopOpacity={0.35}
                                      />
                                      <stop
                                        offset="100%"
                                        stopColor="#ff1f7a"
                                        stopOpacity={0.05}
                                      />
                                    </linearGradient>
                                  </defs>

                                  <XAxis
                                    dataKey="name"
                                    tick={{ fill: "#ffffff", fontSize: 12 }}
                                    axisLine={{
                                      stroke: "rgba(255,255,255,0.4)",
                                    }}
                                  />
                                  <YAxis
                                    domain={[0, 1]}
                                    tickFormatter={(v) => `${v}%`}
                                    tick={{ fill: "#ffffff", fontSize: 12 }}
                                    axisLine={{
                                      stroke: "rgba(255,255,255,0.4)",
                                    }}
                                  />
                                  <Tooltip formatter={(v) => `${v}%`} />

                                  <Area
                                    type="monotone"
                                    dataKey="value"
                                    stroke="#EC1A75"
                                    fill="url(#area)"
                                    strokeWidth={2}
                                  />
                                </AreaChart>
                              </ResponsiveContainer>
                            </div>
                          </div>
                        </div>
                        <div className=" grow">
                          <CardHeader title="Performance by region" />
                          <div className="flex flex-col gap-y-3.5 mt-4 md:mt-8">
                            {performanceByRegion.map((data, _) => (
                              <div
                                className="w-full flex flex-col gap-2"
                                key={data.progress}
                              >
                                <div className="flex justify-between">
                                  <span className="text-white  font-extralight">
                                    {data.region}
                                  </span>
                                  <span className="text-white  font-extralight">
                                    {data.change}
                                  </span>
                                </div>
                                <Progress value={data.progress} />
                              </div>
                            ))}
                          </div>
                        </div>
                      </div>
                    </div>
                    <div className="card">
                      <CardHeader title="Customer journey impact" />
                      <div className="flex flex-col md:flex-row gap-2">
                        {funnelSteps.map((step, index) => {
                          const isFirst = index === 0;
                          return (
                            <div
                              key={step.label}
                              className={`relative flex flex-col justify-center text-white bg-primary  w-full items-center *:flex-1 py-3 ml-0 md:-ml-4.5 ${
                                isFirst
                                  ? "clip-chevron-first rounded-md"
                                  : "clip-chevron rounded-md md:rounded-none"
                              }`}
                              style={{
                                background: gradients[index % gradients.length],
                              }}
                            >
                              <span className="text-[16px] opacity-90">
                                {step.label}
                              </span>
                              <span className="text-[28px] font-bold">
                                {step.value}
                              </span>
                            </div>
                          );
                        })}
                      </div>
                    </div>
                  </div>
                  <div className="card grow">
                    <CardHeader title="AI insights & Recommendations" />
                    <div className="flex flex-col gap-y-5">
                      <AiInlineRecommendation
                        Icon={TrendingUp}
                        text="CTR up 3.1% vs prior 20 days"
                        recommendationType="positive"
                      />
                      <AiInlineRecommendation
                        Icon={TrendingUp}
                        text="Ontario best-performing region (+4.1%)"
                        recommendationType="positive"
                      />
                      <AiInlineRecommendation
                        Icon={CheckCircleIcon}
                        text="Creative A outperforming B by +3.4%)"
                        recommendationType="positive"
                      />
                      <AiInlineRecommendation
                        Icon={Clock12Icon}
                        text="Afternoon highest engagement"
                        recommendationType="positive"
                      />
                      <AiInlineRecommendation
                        Icon={LightbulbIcon}
                        text="Recommendation, shift 10% spend to high traffic regions"
                        recommendationType="positive"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </DashboardModal>
          )}
        </div>
        <div className="card grow">
          <CardHeader title="Path to purchase" />
          <div className="flex flex-row justify-between align-top gap-5 md:gap-2">
            <div>
              <img src={funnelChart} alt="Funnel Chart" className="" />
            </div>
            <div className="flex flex-col gap-2 md:gap-4 justify-between">
              {funnelData.map((data) => {
                return (
                  <div
                    className="flex flex-col text-white gap-1 md:gap-2"
                    key={data.value}
                  >
                    <span className="text-[13px] md:text-[16px] font-bold leading-4">
                      {data.label}
                    </span>
                    <span className="text-[11px] md:text-[14px] font-normal leading-4">
                      {data.sub}
                    </span>
                    <span className="text-[16px] md:text-[30px] font-bold text-primary leading-4">
                      {data.value}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
